weldr/bdcs

Makefile

This allows us to test handling of multiple versions. Also fix the
ORG_NAME for the api-mddb target.

Add 3 versions of bash to the test database

---

importer/db.cabal

This is needed for the latest version of esqueleto and the glib
bindings.

Bump the minimum version of base to 4.9

---

importer/BDCS/CS.hs
importer/BDCS/RPM/Files.hs
importer/Import/RPM.hs

Add a call to ostree_repo_file_ensure_resolved in order to populate the
checksum data before we attempt to read it. Doing this should ensure
that ostree_repo_file_tree_get_contents_checksum does not return null,
so remove the UnexpectedNullPointerReturn and the Maybe wrapper around
the checksum.

Fix retrieving checksums from OstreeRepoFiles

---

importer/BDCS/CS.hs
importer/BDCS/Files.hs
importer/BDCS/Groups.hs
importer/db.cabal
importer/export.hs

This adds a new function and some types to BDCS.CS for retrieving data
from a content store given a checksum from the mddb. There is also a new
function in BDCS.Files to fetch the Files records for a given group id,
returned as a conduit.
Export does not currently handle UID or GID, since those are complicated
and would require it to be run as root anyway, nor does it handle
xattrs, since we don't actually have any of those yet. It will probably
also blow up on anything that isn't a file, directory or symlink.

Add an export program.

---

Makefile
entrypoint.sh
primary-xml-gz

- use env variables to control import
- add make target to build F25 docker image if not present
- copy the new metadata.db out of the volume
- new helper script & Makefile target to import CentOS 7

Make it easier to import CentOS metadata

---

Makefile

Minor improvement, otherwise the `make mddb` command in the for loop will still use the default value.

Set MDDB only if not set

---

importer/Import/Comps.hs
importer/Import/Conduit.hs
importer/Import/RPM.hs
importer/Import/Repodata.hs
importer/db.cabal
importer/import.hs

Remove the filename parameter from ungzipIfCompressed to simplify the pipelines, and instead of having two load functions that do basically the same thing, redo them as a single function that takes a URI and a function in Import.Conduit that figures out what to do with it.

Cut down on code duplication in the import functions

---

Makefile

Kubernetes and friends comes from extras.
Note: extras is also an allowed repository for RHEL depsolving
Note2: depsolver integration tests will report failure:
Unable to satisfy requirement policycoreutils >= 2.5-11

Import CentOS extras repository

---

importer/BDCS/CS.hs

As of version 2017.6, the last argument of
ostree_repo_transaction_set_ref now has a "nullable" annotation,
changing the type for Haskell from Text to Maybe Text. Add a Just
accordingly.

Change a call to match an ostree API change

---

importer/BDCS/Version.hs
importer/db.cabal
importer/tools/depclose.hs
importer/tools/export.hs
importer/tools/import.hs

This shows what git tag and revision it was built from, or uses the
version number from db.cabal

Add git describe version info to the usage output

---

importer/tools/export.hs

For some reason, when we start to process the second thing, we get the
following unhelpful error message:
export: SQLite3 returned ErrorMisuse while attempting to perform bind int64.
I can't find any information on where that comes from, and the sqlite
docs just say you are trying to use the library incorrectly.  Whatever.
Reworking the loops so that runSqlite is on the inside fixes things.

Only process one thing per invocation of runSqlite in export.

---

.travis.yml

Otherwise it doesn't pick up the .hlint.yaml configuration file.
Don't need to run it on haskell-rpm, that is an embedded library and
linting on it should be done upstream.
Also remove --enable-library-coverage to quiet a warning that it is
deprecated and to use --enable-coverage instead.

Travis should run hlint from the importer directory

---

importer/BDCS/CS.hs

This is necessary for being able to mirror the ostree repo.

Regenerate the summary after committing to the content store.

---

Makefile
entrypoint.sh

Just like with the metadata repo, it may be handy to be able to have
multiple content stores around.  This patch should allow you do that.

Allow defining the content store name from the Makefile.

---

Makefile

The latter environment variable will not be set when sudo is involved,
unless you configure sudo to pass it through.  The former is always set
by make.

Use CURDIR in the Makefile instead of PWD.

---

Dockerfile.build
importer/cabal.config

This should cause persistent-sqlite to be built with the system sqlite
library, insted of the very old copy it includes.  This is enough to do
it in local testing.  Hopefully it is enough to do it when make and
docker are involved.

Add a project-level cabal.config file.

---

importer/BDCS/CS.hs
importer/Import/RPM.hs
importer/db.cabal
importer/tools/export.hs

This way you can export to a directory without having to worry about being root, because /usr/bin is 0555 or whatever. Still can't read some of it as non-root afterwards, but what can you do.

Directory export permissions

---

Makefile
importer/Import/Repodata.hs

In e18682d we've lost the ability to append slash to base repo URLs if it is not present. Which leads to the following error:
```
./importer/dist/build/import/import metadata.db cs.repo http://mirror.centos.org/centos/7/os/x86_64
import: ParseError {errorContexts = [], errorMessage = "Failed reading: takeWhile1", errorPosition = 1:1}
```
I've fixed the Makefile used by Jenkins and also tried to fix the `loadRepoFromURI` function but for some reason I still get the same error. I'm not sure if we need the same change in `loadFromURI` as well. @dashea any suggestions ?

Append slash to repo URIs if not present

---

Dockerfile.build

Otherwise the importer job fails b/c we can't build the Docker image

Dockerfile.build should require ostree 2017.8 same as db.cabal

---

.travis.yml
importer/tests/test_export.sh
importer/tools/export.hs

Starting with a metadata.db and cs.repo with several known packages
we try the following scenarios
- export a non-existing RPM package: should give an error
- export an existing RPM pacakge: content should be the same
as if we tried an ostree checkout of the commit which imported
that very same package. To make it easier on us this is the last
imported package where we just `checkout master`.
- export two existing RPM packages which are in conflict with one
another. Still not sure what needs to happen here.

Add exporter tests

---

Makefile
tests/is_import_busted.py

This is handy during import if we don't want to import all packages from a repo but simply append any new ones that were uploaded in the repository.
NOTE: importer job needs to be updated and pass the EXISTING_MDDB variable to make import-centos. Also it needs to be updated to find the resulting artefacts at mddb/metadata.db

Treat EXISTING_MDDB as URL to pre-existing metadata.db

---

.travis.yml

Brings the time down from around 35 minutes to about 8 minutes. Other things that take notable time to execute:
- install latest systemd for testing: 20 seconds
- build libostree: 50 seconds
- build the project, test and install it: 100 seconds
- hpc-coveralls: 80 seconds, which seems rather long. It may have something to do with the fact that we're parsing coverage for the binaries as well, not sure.

Use cache to speed-up build times

---

importer/BDCS/Exceptions.hs
importer/Import/RPM.hs

Unsigned RPMs will not have a RSASignature header. Ignore the error from
this missing header and continue to import the RPM. SHA1 signatures are
still required.

Ignore errors from missing RSA signatures.

---

Dockerfile

Related to https://github.com/weldr/welder-deployment/pull/12
We need the image names to match the organization name on docker.com otherwise we can't push.

Update the name of base Docker image

---

importer/Export/Ostree.hs

rpm-ostree expects the commit to include a rpm database in
/usr/share/rpm. It doesn't have to contain any packages, though, so
initialize an empty one.

Add an empty rpmdb to ostree exports.

---

.travis.yml

- db.cabal was renamed to bdcs.cabal and tests became tests-bdcs
- there is also a new executable named bdcs-tmpfiles

Update coverage command after renames

---

Makefile

This should make `make importer` copy out the `export` binary in
addition to the `import` binary, so you can play around with the tools
locally if you so desire.
It also makes the `importer` rule depend on Makefile.build, which
doesn't really do anything in this case since `importer` is PHONY and
will rebuild no matter what, but it's kind of best practice to do that
anyway.

Makefile: make `make importer` grab `export` binary

---

importer/BDCS/RPM/Groups.hs
importer/BDCS/RPM/Requirements.hs
importer/BDCS/ReqType.hs
importer/bdcs.cabal

Add a bunch of new values to ReqType.ReqContext for requirements that
are needed to install a package but not necessarily needed to run a
package, and parse the RequireFlags tag to assign each requirement to
one or more contexts.

Save script requirements in a separate context

---

.travis.yml
importer/tests/test_export.sh

Add functional test to verify the contents of exported .tar images
the test will try to extract the tar image inside an empty
directory and then compare that to an ostree checkout like we do
for the other test cases.

Exporter tar image test & .travis.yml fixes

---

importer/BDCS/DB.hs
importer/Import/RPM.hs
importer/bdcs.cabal
importer/tools/depsolve.hs
importer/tools/export.hs
importer/tools/inspect/Commands/Groups.hs
importer/tools/inspect/Commands/Ls.hs
importer/tools/inspect/Commands/Nevras.hs
schema.sql

This sets and checks the user_version pragma in the sqlite database. Also rearrange how runSqlite is used in the rpm import so I don't have to check for errors in as many places.

User version

---

.gitignore
.travis.yml
entrypoint-integration-test.sh
importer/tests/test_depsolve.sh

WIP, do not merge yet!
This is the corresponding integration tests part for #92. Currently failing b/c the test passes only package names to depsolve, but it needs list of nevra.
Question: can we make depsolve accept a list of package names and/or nevra ? How hard would that be?

Depsolve integration tests

---

Makefile

- import or tests may be timing out
- tests could fail and we ignore the exit code
this commit will cause the shell to exit immediately if any of the commands fails as is the case with Jenkins job #137.

Exit immediately in case of errors

---

importer/BDCS/Label/Types.hs
importer/bdcs.cabal
importer/tools/inspect/Commands/Groups.hs
importer/tools/inspect/Commands/Ls.hs
importer/tools/inspect/Commands/Nevras.hs
importer/tools/inspect/Utils/Exceptions.hs
importer/tools/inspect/inspect.hs

Add an ls subcommand option to only print out those files who have a matching file label.  This works with all the various ways of outputting the results.  Also, straighten out a lot of the command line processing and error handling in ls subcommands.  It should be pretty solid now.

 Label match

---

.travis.yml

if this is a pull request we want to make a versioned copy of the
compiled binaries so they can be used by the image export tests
to make sure the PR hasn't broken other components

Always upload artifacts used in other test activities

---

Makefile

also use a local directory instead of docker volume to make it easier to copy the results out.

Update RPM versions used for API mddb

---

src/Import/NPM.hs
src/Import/RPM.hs
src/bdcs.cabal

On the plus side, this fixes some pretty big bugs that we were bound to
hit at some point.  On the middle side, it means our stores will now be
compressed which might require changes to our testing setup.  On the
minus side, it requires s/MonadIO/MonadResource/ in several places.

Update to use the new version of content-store.

---

Dockerfile.integration-test
tests/test_export.sh
tests/test_import.sh

since 29c5a11 we're using a new version of content-store which, as @clumens confirms, is not a valid ostree repo anymore! So modify the tests to not use ostree checkout anymore.
Instead I use
```
rpm -Uhv --root ... --nodeps --noscripts *.rpm
```
to install the RPMs into a directory and compare this directory with the results of the export command!

Don't use ostree checkout when testing exports. Fix #116

---

.travis.yml
Makefile

do this from Makefile so that it also works when running tests in Jenkins. The Jenkins slave or localhost executing this make target must take care to configure the appropriate credentials for S3.

Copy the compiled binaries to S3 from Makefile

---

src/BDCS/Groups.hs
src/tests/BDCS/GroupsSpec.hs

epoch goes before version, separated by a ':', not in front of the
package name.
Also added a test for this.

Fix the groupIdToNevra string

---

Dockerfile.integration-test
entrypoint-integration-test.sh
tests/test_depsolve.sh
tests/test_export.sh
tests/test_import.sh
tests/test_tmpfiles.sh

helps us write cleaner and more structured tests
NOTE: there's a simple test result parser in entrypoint-integration-test.sh so we can exit with non-zero in
case of errors.

Convert shell scripts to beakerlib

---

Dockerfile.build

this is solving a strange problem for me where cabal test reports missing files in the dist/ directory.
ls: cannot access 'dist/package.conf.inplace/bdcs-0.1.0-KjTA9F29TQcI3Cj7E8Etoz.conf': No such file or directory
ls: cannot access 'dist/package.conf.inplace/package.cache': No such file or directory
total 0
?????????? ? ? ? ?            ? bdcs-0.1.0-KjTA9F29TQcI3Cj7E8Etoz.conf
?????????? ? ? ? ?            ? package.cache

Run cabal commands in the same Docker layer

---

src/BDCS/Build/NPM.hs
src/BDCS/DB.hs
src/BDCS/Depclose.hs
src/BDCS/Exceptions.hs
src/BDCS/Export/Ostree.hs
src/BDCS/Export/Utils.hs
src/BDCS/Groups.hs
src/BDCS/Import/Comps.hs
src/BDCS/Import/RPM.hs
src/BDCS/Import/Repodata.hs
src/BDCS/Import/URI.hs
src/BDCS/KeyValue.hs
src/BDCS/RPM/Builds.hs
src/BDCS/RPM/Groups.hs
src/BDCS/RPM/Projects.hs
src/tools/bdcs-tmpfiles.hs
src/tools/bdcs.hs
src/tools/export.hs
src/tools/inspect/inspect.hs

For the most part, these are functions that fail on empty or infinite lists.  Removing their use (largely through pattern matching) gets rid of a class of bugs.

Remove partial functions

---

.travis.yml
Dockerfile
Dockerfile.build
Dockerfile.integration-test
Makefile
entrypoint-integration-test.sh
tests/test_depsolve.sh
tests/test_export.sh
tests/test_import.sh

this should speed up the builds and prevent rebuilding of all Haskell dependencies in Travis.
NOTE: tests on my feature branch fail with:
```
:: [ 15:50:42 ] :: [   LOG    ] :: ---------------  OUTPUT END  ---------------
:: [ 15:50:42 ] :: [   FAIL   ] :: Command './dist/build/bdcs/bdcs import metadata.db /tmp/depsolve.repo file:///tmp/dnf.download.B7A9I6/systemd-233-7.fc26.x86_64.rpm' (Expected 0, got 1)
:: [ 15:50:42 ] :: [  BEGIN   ] :: Running './dist/build/bdcs/bdcs import metadata.db /tmp/depsolve.repo file:///tmp/dnf.download.B7A9I6/systemd-libs-233-7.fc26.x86_64.rpm'
STDOUT: subcommand import does not exist
STDOUT: 
STDOUT: bdcs 97f6666
STDOUT: Usage: bdcs subcommand [args ...]
STDOUT: - subcommands:
STDOUT:       depsolve - print a list of all the dependencies of some object …
```

Share ~/.cabal-sandbox dir between host and docker container

---

Setup.hs
bdcs.cabal

This handles a new type used by Cabal for executable names, and adds
backwards compatibility inside a #if.

Handle changes in Cabal-2.0

---

.dockerignore
Makefile
README.md
src/BDCS/Build/NPM.hs
src/BDCS/Builds.hs
src/BDCS/Files.hs
src/BDCS/GroupKeyValue.hs
src/BDCS/Groups.hs
src/BDCS/Import/RPM.hs
src/BDCS/KeyValue.hs
src/BDCS/Packages.hs
src/BDCS/Scripts.hs
src/BDCS/Sources.hs

Also, remove some outdated Makefile targets and documentation, and apply a lot of hlint suggestions that are only showing up now due to a newer version of hlint being included in a newer docker image.

docker-related changed to bdcs

---

bdcs.cabal

Some cabal file changes to compile warning-free with ghc-8.2, and to continue to work with the versions of libraries now in rawhide.

Rawhide warnings

---

Dockerfile.build
Dockerfile.integration-test
Makefile
entrypoint-integration-test.sh
tests/test_export.sh

this commit merges the build+unit test stage with the integration
test stage so that testing will work again.
Because we mount the local directory to the running
docker container all build/test operations must now happen during
runtime (NOTE: -v mounts read-only during docker build). Without
this change the build stage installs bdcs inside a filesystem layer
which is not accessible to the integration-test container and it
fails.

Compile and test bdcs during docker runtime

---

.gitignore
Makefile
README.md

weld-f25 make target is now weld-fedora.
Add ./rpms to .gitignore since it will often be present.

Update the README and .gitignore

---

src/BDCS/Depclose.hs
src/BDCS/Groups.hs

During depsolve, ignore all data from Enhances, Suggests, Recommends,
and Supplements. All of these weak requirement types are allowed to fail
in one way or another, so by ignoring them and potentially leaving them
out of the final depsolve result, we are still being technically
correct.

Only depsolve over "Must" requirements.

---

bdcs.cabal
src/BDCS/Export.hs
src/BDCS/Export/Utils.hs
src/tools/export.hs

This is needed to add support for calling it from the compose API calls.  The command is still around, but basically as a wrapper for the function.

Convert the export command into a function.

---

src/BDCS/Export/FSTree.hs
src/tests/BDCS/Export/FSTreeSpec.hs
tests/test_export.sh

The FSTree code was erroneously following symlinks and recursing every time it encountered a symlink. It should only do that sometimes.
Separated out the existing symlink cases into symlink vs. symlink (compare paths and targets, like for duplicated files) and symlink vs. placeholder (similar to moving a placeholder to a directory, but this one has to resolve a symlink), and everything else is now treated as an error.

Fix the case of a symlink in the way of a file

---

ChangeLog.md
bdcs.cabal
src/BDCS/CS.hs
src/BDCS/Export.hs
src/BDCS/Export/Customize.hs
src/BDCS/Export/FSTree.hs
src/tests/BDCS/Export/FSTreeSpec.hs

This adds the start of a framework for customizing the content of an export with data that is not contained within the mddb or content-store. The idea of this is that it can be used for configuration directives, similar to what is provided by kickstart or cloud-init, and the configuration can be applied at the time of the export.
Currently the only directive is "WriteFile". We're going to want to add file modification at the very least (for setting passwords, for instance), and probably file deletion, but I figured this was a good place to start.
Bumped the bdcs version to 0.2.2 so that bdcs-api can depend on the API changes.

Export customize

---

ChangeLog.md
bdcs.cabal

Primarily, this is to update the aeson and unordered-containers dependency versions so bdcs-api can build on Fedora 27.

Another release

---

src/BDCS/Export.hs

This is needed to allow using the monad-logger functions from within
bdcs-api.

Add a MonadLogger constraint to export and exportAndCustomize.

---

src/BDCS/DB.hs
src/BDCS/Groups.hs
src/tests/BDCS/GroupsSpec.hs

This runs a SQL LIKE query on the groups table, returning entries that
match the query string. Use % as a wildcard, and _ to match an
individual character.

Add getGroupsLike

---

bdcs.cabal
src/BDCS/Export.hs
src/BDCS/Export/Types.hs
src/BDCS/Export/Utils.hs
src/tools/export.hs

This allows breaking apart the tie between the name of the thing to export and the type of the thing being exported.  It also allows for eliminating string comparisons here and in bdcs-api.  Note that this will also require bumping the minor version because I got rid of supportedOutputs.

Add a new ExportType data type.

---

src/tools/inspect/Utils/Exceptions.hs
src/tools/inspect/subcommands/groups.hs
src/tools/inspect/subcommands/ls.hs
src/tools/inspect/subcommands/nevras.hs

Instead, use throwIO afterwards.  This discards the bad label value that
was given, but I think the error message is enough that the user will be
able to tell what they've done wrong and how to fix it.

Don't throw an exception in the pure option processing code.

---

src/BDCS/Export/Ostree.hs

Doing so requires adding our own withTempDirectory function because this
doesn't require sprinkling MonadMask constraints all over the place.
I'm not really familiar with that so I don't know what adding it will
break.  This way is a little lamer, but not difficult.

Add logging for the dracut call in Ostree.hs.

---

Makefile

because we no longer need them. bdcs is installed via RPM.

Stop uploading artifacts to Amazon S3

---

.jenkins/configure-pre-release-dependencies
bdcs.cabal

if Jenkins was given an upstream artifact it will download it.
Now it's up to bdcs to configure its sandbox to that cabal build
will use the local sources instead of downloading them from
Hackage.

Configure pre-release dependencies for Jenkins
