- importer/BDCS/DB.hs
- importer/BDCS/RPM/Groups.hs
- importer/BDCS/ReqType.hs
- importer/Makefile
- importer/depclose.hs
- importer/export.hs
- importer/import.hs
- importer/tests/Main.hs
This adds a Makefile for running tests with coverage reports and running hlint out of a sandbox.
> Test-related Makefile

- .travis.yml
- README.md
- importer/BDCS/Files.hs
- importer/BDCS/Signatures.hs
- importer/tools/depclose.hs
* some improvement to README
* enable test execution in Travis CI
- run the tests with coverage and send the report to coveralls.io as well
* also added hlint as part of CI and applied some hlint suggestions
> Enable Travis CI and other improvements

- importer/BDCS/CS.hs
- importer/tools/export.hs
The out arguments to ostree_repo_load_file are now correctly marked as
nullable, which for means that the return values from
GI.OSTree.repoLoadFile are all Maybes. Adjust accordingly.
There are probably some still unhandled cases where a file is not a
symlink and does not have content (block/char special, e.g.). Those file
types are now slightly more unhandled than before.
> Handle changes to the OSTree API.

- importer/tools/export.hs
The only difference needed between tar and directory exports is how
content store objects are written to disk, so rearrange the processThing
functions so that both export types share all of the code except for a
conduit sink.
With this, tar exports use the same logic as directory exports for mddb
entries with no checksums, so tar exports now ignore ghost files instead
of bombing out.
The placement the SQL monads is kind of gross since we still haven't
figured out the issue with exporting multiple things with one runSqlite
causing an ErrorMisuse.
> Rearrange export to use more conduits.

- .travis.yml
allows the project to build again
> Build latest libostree in Travis

- .travis.yml
- examples/recipes/atlas.toml
- examples/recipes/development.toml
- examples/recipes/glusterfs.toml
- examples/recipes/http-server.toml
- examples/recipes/jboss.toml
- examples/recipes/kubernetes.toml
- importer/tests/README.md
- importer/tests/requirements.txt
- importer/tests/test_depclose.py
- importer/tests/test_depclose.sh
- importer/tests/test_export.sh
- importer/tests/test_import.sh
Initial infrastructure for testing the executable binaries. Later I will add depclose integration with coverage support.
> Add tests and collect coverage for binaries

- importer/db.cabal
- importer/tests/BDCS/GroupsSpec.hs
- importer/tests/Utils.hs
Also includes a Utils function to help with making ephemeral test
databases.
> Add tests for nevraToGroupId.

- .travis.yml
> Hotfix for libostree compile problem

- importer/BDCS/CS.hs
- importer/Export/Ostree.hs
- importer/Export/Utils.hs
- importer/data/nsswitch-altfiles.conf
- importer/data/tmpfiles-ostree.conf
- importer/db.cabal
- importer/tools/export.hs
It's messy, but it works. And by works I mean I have a login prompt. And by login prompt I mean I can't actually log in because of selinux something.
> Ostree export

- importer/BDCS/Version.hs
- importer/Export/Ostree.hs
- importer/Export/Qcow2.hs
- importer/Export/Utils.hs
- importer/bdcs.cabal
It would also be helpful to rename the importer directory to src, but that will require changes across other projects and also make it look like I touched every source line.  I'm not willing to do that right now.
> Update the cabal file to look more like a real project

- Makefile
- s3reposync.sh
Untested, do NOT merge yet, blocked by s3cmd sync OOM issues
> Make it possible to specify existing ostree store before importing

- importer/BDCS/CS.hs
- importer/BDCS/Depsolve.hs
- importer/BDCS/Label/FileLabels.hs
- importer/BDCS/Label/Utils.hs
- importer/BDCS/RPM/Scripts.hs
- importer/BDCS/Scripts.hs
- importer/Export/Directory.hs
- importer/Export/Ostree.hs
- importer/Export/Qcow2.hs
- importer/Import/Comps.hs
- importer/Import/RPM.hs
- importer/bdcs.cabal
- importer/tests/BDCS/RPM/ProjectsSpec.hs
- importer/tests/BDCS/RPM/SignaturesSpec.hs
- importer/tests/BDCS/RPM/SourcesSpec.hs
- importer/tests/Utils.hs
-Wall doesn't work when specified via cpp-options, apparently. Set -Wall
via ghc-options and fix the warnings.
> Turn compiler warnings back on.

- importer/BDCS/DB.hs
- importer/BDCS/GroupKeyValue.hs
- importer/BDCS/Groups.hs
- importer/BDCS/KeyValue.hs
- importer/BDCS/Scripts.hs
This adds two new functions to BDCS.GroupKeyValue to make fetching key/val data easier. Bonus commit that makes matching nullable columns with Maybes less of a pain.
> New functions for fetching key/val data

- .dockerignore
- .travis.yml
- Dockerfile.build
- Dockerfile.integration-test
- Makefile
- entrypoint-integration-test.sh
- importer/BDCS/RPM/Groups.hs
This deals with the apt-get problems in Travis and moves the testing to Fedora. Also easier to switch CIs in the future.
> Run tests inside Docker containers

- importer/BDCS/Builds.hs
- importer/BDCS/CS.hs
- importer/BDCS/DB.hs
- importer/BDCS/Files.hs
- importer/BDCS/NPM/SemVer.hs
- importer/BDCS/RPM/Groups.hs
- importer/BDCS/Sources.hs
- importer/Build/NPM.hs
- importer/Import/NPM.hs
- importer/Utils/Monad.hs
- importer/bdcs.cabal
- importer/tests/BDCS/DepcloseSpec.hs
- importer/tests/BDCS/GroupsSpec.hs
- importer/tests/BDCS/NPM/SemVerSpec.hs
- importer/tools/import.hs
- importer/tools/migratedb.hs
- schema.sql
This is kinda rough so far but hopefully it's a start.
> Npm import

- Makefile
Will help with the transition to Jenkins
> Add ci target in Makefile

- src/Import/NPM.hs
Haddock tries to parse this comment and fails, so replace it with
something that doesn't fail.
> Make a list in a comment more markup-y

- Dockerfile.build
- Makefile
- entrypoint-integration-test.sh
- tests/test_import.sh
this helps with dnf hanging, possibly due to OOM, midway during the upgrades
> Switch to a Fedora 26 Docker based image

- tests/test_import.sh
Note: do not merge until we have the fix for this!
> New test: when importing from 404 URL exit code should be != 0

- Setup.hs
Cabal-2 has very different expectations for how it can use the package
description during copy/install, but it also adds support for the idea
of libexec executables. Change the configure hook for cabal >= 2.0 to
add a private scope to the libexec executables and remove the copy hook.
> Actually handle changes in cabal-2.0

- bdcs.cabal
- src/BDCS/Export/Ostree.hs
- src/BDCS/Export/Utils.hs
also adjust the internal paths to data files because the RPM file layout adds the data/ subdirectory.
> Add schema.sql as data file so it is included later inside the RPM

- bdcs.cabal
- src/BDCS/Export.hs
- src/BDCS/Export/Customize.hs
- src/BDCS/Export/Directory.hs
- src/BDCS/Export/Ostree.hs
- src/BDCS/Export/Qcow2.hs
- src/BDCS/Export/Tar.hs
- src/BDCS/Export/TmpFiles.hs
- src/BDCS/Export/Utils.hs
- src/BDCS/Utils/Process.hs
- src/tools/bdcs-tmpfiles.hs
For the most part, this just sets us up for logging later on.  I've added MonadLogger constraints to all the functions that I think we will need to log from.  I've added calls to logDebugN in a couple places where it seems handy to be able to tell the status of a compose.  I've also added a function that logs the output of most places where we call an external function.
However there's not yet a lot of useful logging in here.  I'm expecting people to add it as needed over time.
> Add logging to BDCS

- schema.sql
- src/BDCS/DB.hs
- src/BDCS/Import/NPM.hs
- src/BDCS/RPM/Projects.hs
We're not putting anything in this field right now and we don't know how
to get it, so don't require its presense.
> Make the upstream_vcs field optional.

- Dockerfile.build
- Makefile
This is an enabler for being able to rebuild with a codec-rpm tarball coming from a codec-rpm PR. Will work if we use cabal new-build/new-test.
> Switch to cabal new-test
